runtime: java11
instance_class: F2
service: graph-builder
automatic_scaling:
  max_instances: 1
  
# Memory limit, heap size
# env_variables:
#   JAVA_TOOL_OPTIONS: "-XX:MaxRAM=1024m -XX:ActiveProcessorCount=4 -Xmx1024m -XX:+UseSerialGC"