name: Deploy JavaDoc
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Change Gradle Run Permissions
        run: chmod +x ./gradlew
      - name: Generate JavaDoc
        run: ./gradlew javadoc
      - name: Deploy JavaDoc to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          clean: true
          folder: build/docs/javadoc
